# This file was generated by GoReleaser. DO NOT EDIT.
cask "sleepy" do
  version "0.5.6"

  on_macos do
    on_intel do
      sha256 "ee37390a5293b702f8e907c5747c67660d54635aed8626231ff1a74b6efeaadd"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "86a1aca91971603080f533be7bf8637e38124dd00f403b3048391bf23def3d99"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8640f62dffe453322981ed33c31d65284cfd2b107065488e0b52821858d87268"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9d7eaa23c87408c8bb8564415969d79ed48705c4a1c98651c9b9b0cd45c76b3d"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "sleepy"
  desc "Client tooling for the sleepy.run evolutionary code optimization service"
  homepage "https://github.com/fugue-labs/sleepy-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sleepy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sleepy"]
    end
  end

  # No zap stanza required

end
