# This file was generated by GoReleaser. DO NOT EDIT.
cask "sleepy" do
  version "0.5.4"

  on_macos do
    on_intel do
      sha256 "304f739b168bd9dffc90b508042383f412756b93e09b8bd0faa366a8c43fb4e9"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0353eb963980467311db94e385797bccb404a3f9ac7784169099ffc691f47652"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f2dc618ff402a74870f6c4b3fb26bf0b6e574ea95e3fcbd8f26229c4b52002f"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "78a107d5acd41585c8cdeab7da7d7ef964b31e794ed1863f48f7b86eb19e91dc"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "sleepy"
  desc "Client tooling for the sleepy.run evolutionary code optimization service"
  homepage "https://github.com/fugue-labs/sleepy-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sleepy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sleepy"]
    end
  end

  # No zap stanza required

end
