# This file was generated by GoReleaser. DO NOT EDIT.
cask "sleepy" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "152ac63d89d4c57fcdf681d1c53dfa893a22c2359ae1631b306b2f7380c46234"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6d25edc3385e7c5e0df18fa6d9e494d84bca37739ce008c06f9d05499dd81427"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "55a6bdea821c8b9f54b4285334af05a6a72cc89a217b2e5ee4312eb0324af32d"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e14e1913cc3c0f48cb4b7773014f0e9bc5302aa2329c3fd380357a0a008451e7"
      url "https://github.com/fugue-labs/sleepy-releases/releases/download/v#{version}/sleepy_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "sleepy"
  desc "Client tooling for the sleepy.run evolutionary code optimization service"
  homepage "https://github.com/fugue-labs/sleepy-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sleepy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sleepy"]
    end
  end

  # No zap stanza required

end
